### ISSUE TITLE
[ISSUE] TypeError: newChannel.reply is not a function

### ISSUE THREAD

**Issue by ultimatehecker** [ultimatehecker/Cybernetic#45]
This is probably due to updating discord.js from 13.4 straight to 13.8, and there is probably a documentation change

**Comment by Poly-Pixel** [comment]
Not sure what you mean by "documentation change", but from what I see you probably just meant to use `newChannel.send` instead of `newChannel.reply`. (`reply` is only on messages, but `channel.clone` returns a Promise that resolves with a channel, so the object passed into your `.then` function is a channel)
